apiVersion: v1
kind: ConfigMap
metadata:
  name: checkout-config
data: 
  PRODUCT_CATALOG_SERVICE_ADDR: "productcatalogservice:3550"
  CURRENCY_SERVICE_ADDR: "currencyservice:7000"
  CART_SERVICE_ADDR: "cartservice:7070"
  SHIPPING_SERVICE_ADDR: "shippingservice:8081"
  CHECKOUT_SERVICE_ADDR: "checkoutservice:5050"
  PAYMENT_SERVICE_ADDR: "paymentservice:3002"
  EMAIL_SERVICE_ADDR: "emailservice:5001"