apiVersion: v1
kind: ConfigMap
metadata: 
  name: frontend-config
data: 
  PRODUCT_CATALOG_SERVICE_ADDR: "productcatalogservice:3550"
  PAYMENT_SERVICE_ADDR: "paymentservice:3002"
  CURRENCY_SERVICE_ADDR: "currencyservice:7000"
  CART_SERVICE_ADDR: "cartservice:7070"
  RECOMMENDATION_SERVICE_ADDR: "recommendationservice:5002"
  SHIPPING_SERVICE_ADDR: "shippingservice:8081"
  CHECKOUT_SERVICE_ADDR: "checkoutservice:5050"
  AD_SERVICE_ADDR: "adservice:9555"
  SHOPPING_ASSISTANT_SERVICE_ADDR: "shoppingassistantservice:8005"
  EMAIL_SERVICE_ADDR: "emailservice:5001"