apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ijeawele/frontend:v1.0
        ports: 
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: frontend-config
       
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:  
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
        