apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - name: paymentservice
        image: ijeawele/paymentservice:v1.0
        ports:
        - containerPort: 3002
        env:
        - name: PORT
          value: "3002"
        - name: DISABLE_PROFILER
          value: "true"

---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice
spec:
  selector:
    app: paymentservice
  ports:
  - protocol: TCP
    port: 3002
    targetPort: 3002
  type: ClusterIP