apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-assistant-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppingassistantservice
  template:
    metadata:
      labels:
        app: shoppingassistantservice
    spec:
      containers:
      - name: shoppingassistantservice
        image: ijeawele/shoppingassistantservice:v1.0
        ports:
        - containerPort: 8005
        env:
        - name: PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: PROJECT_ID
        - name: REGION
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: REGION
        - name: ALLOYDB_DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: ALLOYDB_DATABASE_NAME
        - name: ALLOYDB_TABLE_NAME
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: ALLOYDB_TABLE_NAME
        - name: ALLOYDB_CLUSTER_NAME
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: ALLOYDB_CLUSTER_NAME
        - name: ALLOYDB_INSTANCE_NAME
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: ALLOYDB_INSTANCE_NAME
        - name: ALLOYDB_SECRET_NAME
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: ALLOYDB_SECRET_NAME

---

apiVersion: v1
kind: Service
metadata:
  name: shoppingassistantservice
spec:
  selector:
    app: shoppingassistantservice
  ports:
  - protocol: TCP
    port: 8005
    targetPort: 8005
  type: ClusterIP