apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: checkout-external-secret
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: aws-secrets-store
    kind: SecretStore
  target:
    name: checkout-config-secret
    creationPolicy: Owner
  data:
  - secretKey: PRODUCT_CATALOG_SERVICE_ADDR
    remoteRef:
      key: microservices/services
      property: PRODUCT_CATALOG_SERVICE_ADDR
  - secretKey: CURRENCY_SERVICE_ADDR
    remoteRef:
      key: microservices/services
      property: CURRENCY_SERVICE_ADDR
  - secretKey: CART_SERVICE_ADDR
    remoteRef:
      key: microservices/services
      property: CART_SERVICE_ADDR
  - secretKey: SHIPPING_SERVICE_ADDR
    remoteRef:
      key: microservices/services
      property: SHIPPING_SERVICE_ADDR
  - secretKey: CHECKOUT_SERVICE_ADDR
    remoteRef:
      key: microservices/services
      property: CHECKOUT_SERVICE_ADDR
  - secretKey: PAYMENT_SERVICE_ADDR
    remoteRef:
      key: microservices/services
      property: PAYMENT_SERVICE_ADDR
  - secretKey: EMAIL_SERVICE_ADDR
    remoteRef:
      key: microservices/services
      property: EMAIL_SERVICE_ADDR