apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: recommendation-external-secret
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: aws-secrets-store
    kind: SecretStore
  target:
    name: recommendation-config-secret
    creationPolicy: Owner
  data:
  - secretKey: PRODUCT_CATALOG_SERVICE_ADDR
    remoteRef:
      key: microservices/services
      property: PRODUCT_CATALOG_SERVICE_ADDR