# Default values for online-boutique microservices

# Global settings
global:
  namespace: prod
  pullPolicy: IfNotPresent

# Individual microservices configuration
services:
  frontend:
    enabled: true
    replicaCount: 2
    image:
      repository: ijeawele/frontend
      tag: v1.0
    service:
      type: ClusterIP
      port: 8080
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 10
      targetCPUUtilizationPercentage: 70

  cartservice:
    enabled: true
    replicaCount: 1
    image:
      repository: ijeawele/cartservice
      tag: v1.0
    service:
      type: ClusterIP
      port: 7070
    resources:
      requests:
        memory: "64Mi"
        cpu: "200m"
      limits:
        memory: "128Mi"
        cpu: "300m"
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 50

  checkoutservice:
    enabled: true
    replicaCount: 1
    image:
      repository: ijeawele/checkoutservice
      tag: v1.0
    service:
      type: ClusterIP
      port: 5050
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
      autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 50

  productcatalogservice:
    enabled: true
    replicaCount: 1
    image:
      repository: ijeawele/productcatalogservice
      tag: v1.0
    service:
      type: ClusterIP
      port: 3550
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 5
      targetCPUUtilizationPercentage: 60

  currencyservice:
    enabled: true
    replicaCount: 1
    image:
      repository: ijeawele/currencyservice
      tag: v1.0
    service:
      type: ClusterIP
      port: 7000
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 50

  paymentservice:
    enabled: true
    replicaCount: 1
    image:
      repository: ijeawele/paymentservice
      tag: v1.0
    service:
      type: ClusterIP
      port: 3002
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 50

  shippingservice:
    enabled: true
    replicaCount: 1
    image:
      repository: ijeawele/shippingservice
      tag: v1.0
    service:
      type: ClusterIP
      port: 8081
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 50

  emailservice:
    enabled: true
    replicaCount: 1
    image:
      repository: ijeawele/emailservice
      tag: v1.0
    service:
      type: ClusterIP
      port: 5001
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 50

  recommendationservice:
    enabled: true
    replicaCount: 1
    image:
      repository: ijeawele/recommendationservice
      tag: v1.0
    service:
      type: ClusterIP
      port: 5002
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 50

  adservice:
    enabled: true
    replicaCount: 1
    image:
      repository: ijeawele/adservice
      tag: v1.0
    service:
      type: ClusterIP
      port: 9555
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 50

  redis:
    enabled: true
    replicaCount: 1
    image:
      repository: redis
      tag: "6.2"
    service:
      type: ClusterIP
      port: 6379
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 50

# Shared ConfigMaps
configMaps:
  serviceAddresses:
    PRODUCT_CATALOG_SERVICE_ADDR: "productcatalogservice:3550"
    CURRENCY_SERVICE_ADDR: "currencyservice:7000"
    CART_SERVICE_ADDR: "cartservice:7070"
    RECOMMENDATION_SERVICE_ADDR: "recommendationservice:5002"
    SHIPPING_SERVICE_ADDR: "shippingservice:8081"
    CHECKOUT_SERVICE_ADDR: "checkoutservice:5050"
    AD_SERVICE_ADDR: "adservice:9555"
    PAYMENT_SERVICE_ADDR: "paymentservice:3002"
    EMAIL_SERVICE_ADDR: "emailservice:5001"
    REDIS_HOST: "redis:6379"

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: your-domain.com
      paths:
        - path: /
          pathType: Prefix
          service: frontend
          port: 8080
  tls: []

# Global resource defaults
defaultResources:
  requests:
    memory: "64Mi"
    cpu: "100m"
  limits:
    memory: "128Mi"
    cpu: "200m"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

  # Add this to your values.yaml file at the top level
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
  # targetMemoryUtilizationPercentage: 80
