# Default values for online-boutique microservices

# Global settings
global:
  namespace: prod
  pullPolicy: IfNotPresent

# Individual microservices configuration
services:
  frontend:
    enabled: true
    replicaCount: 2
    image:
      repository: ijeawele/frontend
      tag: v1.0
    service:
      type: ClusterIP
      port: 8080
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 10
      targetCPUUtilizationPercentage: 70

  cartservice:
    enabled: true
    replicaCount: 1
    image:
      repository: ijeawele/cartservice
      tag: v1.0
    service:
      type: ClusterIP
      port: 7070
    resources:
      requests:
        memory: "64Mi"
        cpu: "200m"
      limits:
        memory: "128Mi"
        cpu: "300m"
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 50

  checkoutservice:
    enabled: true
    replicaCount: 1
    image:
      repository: ijeawele/checkoutservice
      tag: v1.0
    service:
      type: ClusterIP
      port: 5050
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 50

  productcatalogservice:
    enabled: true
    replicaCount: 1
    image:
      repository: ijeawele/productcatalogservice
      tag: v1.0
    service:
      type: ClusterIP
      port: 3550
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 5
      targetCPUUtilizationPercentage: 60

  currencyservice:
    enabled: true
    replicaCount: 1
    image:
      repository: ijeawele/currencyservice
      tag: v1.0
    service:
      type: ClusterIP
      port: 7000
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 50

  paymentservice:
    enabled: true
    replicaCount: 1
    image:
      repository: ijeawele/paymentservice
      tag: v1.0
    service:
      type: ClusterIP
      port: 3002
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 50

  shippingservice:
    enabled: true
    replicaCount: 1
    image:
      repository: ijeawele/shippingservice
      tag: v1.0
    service:
      type: ClusterIP
      port: 8081
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 50

  emailservice:
    enabled: true
    replicaCount: 1
    image:
      repository: ijeawele/emailservice
      tag: v1.0
    service:
      type: ClusterIP
      port: 5001
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 50

  recommendationservice:
    enabled: true
    replicaCount: 1
    image:
      repository: ijeawele/recommendationservice
      tag: v1.0
    service:
      type: ClusterIP
      port: 5002
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 50

  adservice:
    enabled: true
    replicaCount: 1
    image:
      repository: ijeawele/adservice
      tag: v1.0
    service:
      type: ClusterIP
      port: 9555
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 50

  redis:
    enabled: true
    replicaCount: 1
    image:
      repository: redis
      tag: "6.2"
    service:
      type: ClusterIP
      port: 6379
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 50

# External Secrets configuration
externalSecrets:
  enabled: true
  refreshInterval: 15s
  secretStore:
    name: aws-secrets-store
  aws:
    region: us-east-1
    credentialsSecret: aws-credentials  # References existing secret
    secretKey: microservices/services   # AWS Secrets Manager key name

  secretKeys:
    - PRODUCT_CATALOG_SERVICE_ADDR
    - CURRENCY_SERVICE_ADDR
    - CART_SERVICE_ADDR
    - RECOMMENDATION_SERVICE_ADDR
    - SHIPPING_SERVICE_ADDR
    - CHECKOUT_SERVICE_ADDR
    - AD_SERVICE_ADDR
    - PAYMENT_SERVICE_ADDR
    - EMAIL_SERVICE_ADDR
    - SHOPPING_ASSISTANT_SERVICE_ADDR
    - REDIS_HOST

# Ingress configuration
ingress:
  enabled: true
  className: "app-nginx"
  annotations: {}
  hosts:
    - host: a713f33313acb42b681e575bfcd5f6d4-f60753852b1729e5.elb.us-east-1.amazonaws.com 
      http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: frontend
              port:
                number: 8080
        - path: /static
          pathType: Prefix
          backend:
            service:
              name: frontend
              port:
                number: 8080
        - path: /api/checkout(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: checkoutservice
              port:
                number: 5050
        - path: /api/cart(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: cartservice
              port:
                number: 7070
        - path: /api/products(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: productcatalogservice
              port:
                number: 3550
        - path: /api/currency(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: currencyservice
              port:
                number: 7000
        - path: /api/recommendation(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: recommendationservice
              port:
                number: 5002
        - path: /api/shipping(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: shippingservice
              port:
                number: 8081
        - path: /api/payment(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: paymentservice
              port:
                number: 3002
        - path: /api/email(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: emailservice
              port:
                number: 5001
        - path: /api/ads(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: adservice
              port:
                number: 9555
        - path: /api/shopping-assistant(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: shoppingassistantservice
              port:
                number: 8005
  tls: []

# Global resource defaults
defaultResources:
  requests:
    memory: "64Mi"
    cpu: "100m"
  limits:
    memory: "128Mi"
    cpu: "200m"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

  # Add this to your values.yaml file at the top level
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
  # targetMemoryUtilizationPercentage: 80
