# templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-addresses
data:
{{- range $key, $value := .Values.configMaps.serviceAddresses }}
  {{ $key }}: {{ $value | quote }}
{{- end }}

