{{- range $serviceName, $config := .Values.services }}
{{- if $config.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $serviceName }}-deployment
  labels:
    app: {{ $serviceName }}
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
spec:
  {{- if not $config.autoscaling.enabled }}
  replicas: {{ $config.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ $serviceName }}
  template:
    metadata:
      labels:
        app: {{ $serviceName }}
    spec:
      containers:
      - name: {{ $serviceName }}
        image: "{{ $config.image.repository }}:{{ $config.image.tag }}"
        imagePullPolicy: {{ $.Values.global.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ $config.service.port }}
          protocol: TCP
        {{- if $config.resources }}
        resources:
          {{- toYaml $config.resources | nindent 10 }}
        {{- end }}
        {{- if eq $serviceName "frontend" }}
        envFrom:
        - configMapRef:
            name: service-addresses
        {{- end }}
{{- end }}
{{- end }}