{{- range $serviceName, $config := .Values.services }}
{{- if $config.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $serviceName }}-deployment
  labels:
    app: {{ $serviceName }}
    chart: {{ include "my-online-boutique.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  {{- if not $config.autoscaling.enabled }}
  replicas: {{ $config.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ $serviceName }}
      release: {{ $.Release.Name }}
  template:
    metadata:
      labels:
        app: {{ $serviceName }}
        release: {{ $.Release.Name }}
    spec:
      containers:
      - name: {{ $serviceName }}
        image: "{{ $config.image.repository }}:{{ $config.image.tag }}"
        ports:
        - containerPort: {{ $config.service.port }}
        {{- if $config.resources }}
        resources:
          {{- toYaml $config.resources | nindent 10 }}
        {{- end }}
        {{- if eq $serviceName "frontend" }}
        envFrom:
        - configMapRef:
            name: service-addresses
        {{- end }}
        {{- if eq $serviceName "checkoutservice" }}
        envFrom:
        - configMapRef:
            name: service-addresses
        {{- end }}
        {{- if eq $serviceName "paymentservice" }}
        env:
        - name: PORT
          value: "{{ $config.service.port }}"
        envFrom:
        - configMapRef:
            name: service-addresses
        {{- end }}
{{- end }}
{{- end }}
