{{- if .Values.externalSecrets.enabled }}
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecrets.secretStore.name }}
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.externalSecrets.aws.region }}
      auth:
        secretRef:
          accessKeyID:
            name: {{ .Values.externalSecrets.aws.credentialsSecret }}
            key: access-key-id
          secretAccessKey:
            name: {{ .Values.externalSecrets.aws.credentialsSecret }}
            key: secret-access-key

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: service-addresses-external-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: SecretStore
  target:
    name: service-addresses-secret
    creationPolicy: Owner
  data:
  {{- range .Values.externalSecrets.secretKeys }}
  - secretKey: {{ . }}
    remoteRef:
      key: {{ $.Values.externalSecrets.aws.secretKey }}
      property: {{ . }}
  {{- end }}
{{- end }}