{{- range $serviceName, $config := .Values.services }}
{{- if $config.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
  labels:
    app: {{ $serviceName }}
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
spec:
  type: {{ $config.service.type }}
  ports:
    - port: {{ $config.service.port }}
      targetPort: {{ $config.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ $serviceName }}
{{- end }}
{{- end }}
