apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    # NGINX Ingress Controller
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "8m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    
    # Security headers
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header X-Frame-Options "SAMEORIGIN" always;
      add_header X-Content-Type-Options "nosniff" always;
      add_header X-XSS-Protection "1; mode=block" always;
      add_header Referrer-Policy "strict-origin-when-cross-origin" always;
      add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    
    # Rate limiting
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-rps: "10"
    
    # Certificate management
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - a6c5aed73ecef480f97a2134d5beee3e-9240314fd9a7469e.elb.us-east-1.amazonaws.com  
    secretName: app-tls-secret
  rules:
  - host: a6c5aed73ecef480f97a2134d5beee3e-9240314fd9a7469e.elb.us-east-1.amazonaws.com  
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 8080
      - path: /static
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 8080
      - path: /api/checkout
        pathType: Prefix
        backend:
          service:
            name: checkoutservice
            port:
              number: 5050
      - path: /api/cart
        pathType: Prefix
        backend:
          service:
            name: cartservice
            port:
              number: 7070
      - path: /api/products
        pathType: Prefix
        backend:
          service:
            name: productcatalogservice
            port:
              number: 3550
      - path: /api/currency
        pathType: Prefix
        backend:
          service:
            name: currencyservice
            port:
              number: 7000
      - path: /api/recommendation
        pathType: Prefix
        backend:
          service:
            name: recommendationservice
            port:
              number: 5002
      - path: /api/shipping
        pathType: Prefix
        backend:
          service:
            name: shippingservice
            port:
              number: 8081
      - path: /api/payment
        pathType: Prefix
        backend:
          service:
            name: paymentservice
            port:
              number: 3002
      - path: /api/email
        pathType: Prefix
        backend:
          service:
            name: emailservice
            port:
              number: 5001
      - path: /api/ads
        pathType: Prefix
        backend:
          service:
            name: adservice
            port:
              number: 9555
      - path: /api/shopping-assistant
        pathType: Prefix
        backend:
          service:
            name: shoppingassistantservice
            port:
              number: 8005

