services:
  emailservice:
    build:
      context: ./emailservice
      dockerfile: Dockerfile
    container_name: emailservice
    ports:
      - "5001:5001"

  shippingservice:
    build:
      context: ./shippingservice
      dockerfile: Dockerfile
    container_name: shippingservice
    ports:
      - "8081:8081"

  recommendationservice:
    build:
      context: ./recommendationservice
      dockerfile: Dockerfile
    container_name: recommendationservice
    ports:
      - "5002:5002"
    environment:
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550

  cartservice:
    build:
      context: ./cartservice/src
      dockerfile: Dockerfile
    container_name: cartservice
    ports:
      - "7070:7070"
    environment:
      - REDIS_HOST=redis:6379

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  

  productcatalogservice:
    build:
      context: ./productcatalogservice
      dockerfile: Dockerfile
    container_name: productcatalogservice
    ports:
      - "3550:3550"

  currencyservice:
    build:
      context: ./currencyservice
      dockerfile: Dockerfile
    container_name: currencyservice
    ports:
      - "7000:7000"
    environment:
      - DISABLE_PROFILER=true

  paymentservice:
    build:
      context: ./paymentservice
      dockerfile: Dockerfile
    container_name: paymentservice
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - DISABLE_PROFILER=true

  checkoutservice:
    build:
      context: ./checkoutservice
      dockerfile: Dockerfile
    container_name: checkoutservice
    ports:
      - "5050:5050"
    environment:
      - SHIPPING_SERVICE_ADDR=shippingservice:8081
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - CART_SERVICE_ADDR=cartservice:7070
      - PAYMENT_SERVICE_ADDR=paymentservice:3002
      - CURRENCY_SERVICE_ADDR=currencyservice:7000
      - EMAIL_SERVICE_ADDR=emailservice:5001

  adservice:
    build:
      context: ./adservice
      dockerfile: Dockerfile
    container_name: adservice
    ports:
      - "9555:9555"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:8080"
    environment:
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - PAYMENT_SERVICE_ADDR=paymentservice:3002
      - CURRENCY_SERVICE_ADDR=currencyservice:7000
      - CART_SERVICE_ADDR=cartservice:7070
      - CHECKOUT_SERVICE_ADDR=checkoutservice:5050
      - RECOMMENDATION_SERVICE_ADDR=recommendationservice:5002
      - SHIPPING_SERVICE_ADDR=shippingservice:8081
      - AD_SERVICE_ADDR=adservice:9555
      - EMAIL_SERVICE_ADDR=emailservice:5001
      - SHOPPING_ASSISTANT_SERVICE_ADDR=shoppingassistantservice:8005

  shoppingassistantservice:
    build:
      context: ./shoppingassistantservice
      dockerfile: Dockerfile
    container_name: shoppingassistantservice
    ports:
      - "8005:8005"
    environment:
      - DISABLE_PROFILER=true
      - PROJECT_ID=dummy-project-id
      - REGION=dummy-region
      - ALLOYDB_DATABASE_NAME=dummy-database-name
      - ALLOYDB_TABLE_NAME=dummy-table-name
      - ALLOYDB_CLUSTER_NAME=dummy-cluster-name
      - ALLOYDB_INSTANCE_NAME=dummy-instance-name
      - ALLOYDB_SECRET_NAME=dummy-secret-name
volumes:
  redis_data: